### ISSUE TITLE
Meta: Services-API enhancements

### ISSUE THREAD

**Issue by tauli** [impfen/services-inoeg#9]
- [x] https://github.com/kiebitz-oss/services-inoeg/issues/17
 - [x] https://github.com/kiebitz-oss/services-inoeg/issues/29
 - [x] https://github.com/kiebitz-oss/services-inoeg/issues/21
 - [x] https://github.com/kiebitz-oss/services-inoeg/issues/26
 - [x] https://github.com/kiebitz-oss/services-inoeg/issues/12
 - [x] #10
 - [x] add unverifiedProviderData to the checkData()-returnType

**Comment by benbender** [comment]
If possible:
 - add unverifiedProviderData to the checkData()-returnType
